name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  firebase-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        uses: w9jds/firebase-action@v13.5.1
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
